[refactor/WF-106]: refactor param options in controller
Illusory-Team/work-fly-server pull request #22
Opened 2023-04-21 18:05 UTC by Leahim2085

Переписал guard для acces токена: добавил объект c id пользователя из расшифрованного токена в параметр user объекта request. Убрал param опции в контроллере, теперь id юзера достаю из объекта request.

2023-04-22 11:24 UTC, Stepasha419a requested changes
доделывай с другими эндпоинтами, ты только 2 сделал

2023-04-22 17:49 UTC, Stepasha419a requested changes

2023-04-22 17:49 UTC, Stepasha419a commented on src/folders/appearance/folder-appearances.controller.ts
> +    return this.folderAppearancesService.patchOne(accessToken, req.user['id'], dto);
этот эндпоинт не относится к user

2023-04-22 17:49 UTC, Stepasha419a commented on src/folders/folders.controller.ts
> +    return this.foldersService.patchOne(accessToken, req.user['id'], dto);
этот эндпоинт не относится к user

2023-04-22 20:02 UTC, Stepasha419a requested changes

2023-04-22 20:02 UTC, Stepasha419a commented on src/companies/companies.controller.ts
> +    return this.companiesService.patchOne(accessToken, req.user['id'], dto);
опять упустил, там используется id компании, не userId!!

2023-04-22 20:02 UTC, Stepasha419a commented on src/companies/companies.controller.ts
> +    return this.companiesService.findById(req.user['id']);
там используется id компании, не userId!!

2023-04-23 09:01 UTC, Stepasha419a approved these changes

2023-04-23 09:34 UTC, edword03 approved these changes

2023-04-23 09:36 UTC, merged