[refactor/wf-120]:  refactor absolute paths
Illusory-Team/work-fly-server pull request #26
Opened 2023-05-09 19:13 UTC by Leahim2085

## Task name
Refactor absolute paths
### Describe task
- Added custom aliases for imports
- Refactored base url fow imports
- Refactored all bad imports
### Issue ticket number and link
WF-120
https://illusory-team.atlassian.net/browse/WF-120?atlOrigin=eyJpIjoiNmM1MjQ3MWMxY2QxNDc5M2IxOTZlMjExOWY1OTQyNDYiLCJwIjoiaiJ9
### Screens/videos (if there)

### TBD (if there)

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [ ] If it is a core feature, I have added thorough tests.

2023-05-09 19:58 UTC, Stepasha419a requested changes
поменяй все алиасы, где есть index.ts на просто import ... from '@decorators', пример в tsconfig: "@guards": ["common/guards/index"], чтобы не писать /index

2023-05-10 19:26 UTC, Stepasha419a requested changes
прочитай еще раз, что я написал тогда, ты сделал неправильно

2023-05-11 15:10 UTC, Stepasha419a requested changes

2023-05-11 15:10 UTC, Stepasha419a commented on src/folders/dto/user-folder.dto.ts
> +import { PureUserDto } from 'users/dto/pure-user.dto';
users/dto, я знаю, что там так и было, просто переделай

2023-05-11 17:17 UTC, dmitryduy commented on src/prisma/prisma.service.ts
> +    await this.$disconnect();
Как это связано с рефактором путей?

2023-05-11 17:20 UTC, dmitryduy commented on src/app.module.ts
> +import { FolderAppearancesModule } from 'folders/appearance/folder-appearances.module';
почему какие то пути начинаются с собачки, а какие то без нее?

2023-05-11 17:21 UTC, dmitryduy commented on src/common/decorators/index.ts
> +export * from './is-phone-number.decorator';
тут нужна эта пустая строка?

2023-05-11 17:36 UTC, merged